# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. 
on:
  schedule:
    - cron: "11 */2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.1.1
        with:
          timezone: Asia/Shanghai

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo main.sh
          bash main.sh
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply if run changes
